// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using RedSquirrel.Data;
using System;

namespace redsquirrel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171203171730_owners")]
    partial class owners
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("RedSquirrel.Data.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("RedSquirrel.Data.Entities.FoodConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FirstUnitId");

                    b.Property<int?>("FoodId");

                    b.Property<double>("Ratio");

                    b.Property<int?>("SecondUnitId");

                    b.HasKey("Id");

                    b.HasIndex("FirstUnitId");

                    b.HasIndex("FoodId");

                    b.HasIndex("SecondUnitId");

                    b.ToTable("FoodConversion");
                });

            modelBuilder.Entity("RedSquirrel.Data.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<int?>("FoodId");

                    b.Property<int?>("LocationId");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("RedSquirrel.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("RedSquirrel.Data.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("RedSquirrel.Data.Entities.UnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FirstUnitId");

                    b.Property<double>("Ratio");

                    b.Property<int?>("SecondUnitId");

                    b.HasKey("Id");

                    b.HasIndex("FirstUnitId");

                    b.HasIndex("SecondUnitId");

                    b.ToTable("UnitConversion");
                });

            modelBuilder.Entity("RedSquirrel.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RedSquirrel.Data.Entities.FoodConversion", b =>
                {
                    b.HasOne("RedSquirrel.Data.Entities.Unit", "FirstUnit")
                        .WithMany()
                        .HasForeignKey("FirstUnitId");

                    b.HasOne("RedSquirrel.Data.Entities.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId");

                    b.HasOne("RedSquirrel.Data.Entities.Unit", "SecondUnit")
                        .WithMany()
                        .HasForeignKey("SecondUnitId");
                });

            modelBuilder.Entity("RedSquirrel.Data.Entities.Inventory", b =>
                {
                    b.HasOne("RedSquirrel.Data.Entities.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId");

                    b.HasOne("RedSquirrel.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("RedSquirrel.Models.User", "User")
                        .WithMany("Inventories")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("RedSquirrel.Data.Entities.UnitConversion", b =>
                {
                    b.HasOne("RedSquirrel.Data.Entities.Unit", "FirstUnit")
                        .WithMany()
                        .HasForeignKey("FirstUnitId");

                    b.HasOne("RedSquirrel.Data.Entities.Unit", "SecondUnit")
                        .WithMany()
                        .HasForeignKey("SecondUnitId");
                });
#pragma warning restore 612, 618
        }
    }
}
